-- =============================================================================
-- FITLIFE — MIGRATION 001: shop_products (Gym Shop inventory)
-- =============================================================================
-- NON-DESTRUCTIVE: safe to run on an existing database — creates the table only
-- if it doesn't exist and never touches other data.
--
-- Run in the Supabase SQL Editor. Consumed by:
--   src/lib/supabaseData.js  (fetchAllData → shopProducts, db.* helpers)
--   src/context/GymDataContext.jsx (shopProducts, saveShopProduct, deleteShopProduct)
--   src/pages/GymShop.jsx
-- =============================================================================

create table if not exists public.shop_products (
  id          bigint generated by default as identity primary key,
  name        text not null,
  category    text not null default 'Gym Wear'
              check (category in ('Gym Wear', 'Food')),
  brand       text,                                  -- e.g. 'FitLife', 'Optimum Nutrition'
  price       numeric(10,2) not null default 0,       -- selling price, BDT
  cost        numeric(10,2) not null default 0,       -- wholesale cost, BDT (margin calc)
  stock       int not null default 0,
  unit        text not null default 'pcs',            -- 'pcs' | 'kg' | 'packet' | 'bottle'
  size        text,                                   -- apparel only: 'S' | 'M' | 'L' | 'XL' | 'XXL'
  image_url   text,
  description text,
  status      text not null default 'Active'
              check (status in ('Active', 'Draft', 'Archived')),
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists idx_shop_products_category on public.shop_products(category);
create index if not exists idx_shop_products_status    on public.shop_products(status);

-- updated_at maintenance (same pattern as schema.sql section 12)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_shop_products_updated_at on public.shop_products;
create trigger trg_shop_products_updated_at
  before update on public.shop_products
  for each row execute function public.set_updated_at();

-- RLS: same model as every other admin-panel table (authenticated = full access)
alter table public.shop_products enable row level security;

drop policy if exists "authenticated all on shop_products" on public.shop_products;
create policy "authenticated all on shop_products"
  on public.shop_products for all to authenticated
  using (true) with check (true);

grant usage on schema public to authenticated;
grant all on public.shop_products to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Seed: gym wear + food/supplement sample catalog (idempotent)
-- ---------------------------------------------------------------------------
insert into public.shop_products
  (name, category, brand, price, cost, stock, unit, size, image_url, description, status)
values
  -- Gym wear
  ('FitLife Performance T-Shirt', 'Gym Wear', 'FitLife',  890.00,  450.00, 42, 'pcs', 'M',
   'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80',
   'Moisture-wicking breathable tee with FitLife logo print.', 'Active'),
  ('FitLife Performance T-Shirt', 'Gym Wear', 'FitLife',  890.00,  450.00, 35, 'pcs', 'L',
   'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80',
   'Moisture-wicking breathable tee with FitLife logo print.', 'Active'),
  ('Flex-Fit Training Shorts', 'Gym Wear', 'FitLife', 1150.00,  600.00, 28, 'pcs', 'L',
   'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80',
   '4-way stretch shorts with zip pockets and drawstring waist.', 'Active'),
  ('Compression Leggings', 'Gym Wear', 'FitLife', 1450.00,  780.00, 22, 'pcs', 'M',
   'https://images.unsplash.com/photo-1506634572416-48cdfe530110?w=800&auto=format&fit=crop&q=80',
   'High-waist squat-proof compression leggings.', 'Active'),
  ('Lifting Wrist Wraps (Pair)', 'Gym Wear', 'IronGrip', 650.00,  300.00, 60, 'pcs', null,
   'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&auto=format&fit=crop&q=80',
   '18" heavy-duty cotton wrist wraps for bench & OHP.', 'Active'),
  ('Anti-Slip Workout Gloves', 'Gym Wear', 'IronGrip',  750.00,  350.00, 4,  'pcs', 'L',
   'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=800&auto=format&fit=crop&q=80',
   'Padded palm, open back, adjustable velcro strap.', 'Active'),
  ('Gym Duffel Bag 40L', 'Gym Wear', 'FitLife',      2200.00, 1200.00, 15, 'pcs', null,
   'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
   'Shoe compartment, wet-pocket, and padded strap.', 'Active'),
  ('FitLife Logo Cap', 'Gym Wear', 'FitLife',         550.00,  250.00, 0,  'pcs', null,
   'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
   'Breathable 6-panel cap with embroidered logo.', 'Active'),

  -- Food / supplements
  ('Whey Protein Isolate 2lb', 'Food', 'Optimum Nutrition', 4500.00, 3600.00, 25, 'bottle', null,
   'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&auto=format&fit=crop&q=80',
   '24g protein per scoop, chocolate flavour. 30 servings.', 'Active'),
  ('Mass Gainer 5lb', 'Food', 'Optimum Nutrition',  5800.00, 4700.00, 12, 'bottle', null,
   'https://images.unsplash.com/photo-1579722821273-0f6c1ddde163?w=800&auto=format&fit=crop&q=80',
   '1250 cal per serving mass formula, vanilla.', 'Active'),
  ('Banana (per kg)', 'Food', 'Local',                120.00,   80.00, 40, 'kg',   null,
   'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80',
   'Fresh local bananas — quick pre-workout carbs.', 'Active'),
  ('Boiled Eggs (per kg)', 'Food', 'Local',           240.00,  160.00, 18, 'kg',   null,
   'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&auto=format&fit=crop&q=80',
   'Fresh boiled eggs, 6g protein each.', 'Active'),
  ('Grilled Chicken Box 300g', 'Food', 'FitLife Kitchen', 320.00, 190.00, 10, 'packet', null,
   'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&auto=format&fit=crop&q=80',
   'Meal-prep box: 300g chicken breast, 150g rice, salad.', 'Active'),
  ('Protein Bar 60g', 'Food', 'FitLife',              250.00,  150.00, 5,  'packet', null,
   'https://images.unsplash.com/photo-1622484212850-eb596d769edc?w=800&auto=format&fit=crop&q=80',
   '20g protein, low sugar. Chocolate peanut butter.', 'Active'),
  ('Isotonic Sports Drink 500ml', 'Food', 'FitLife',  150.00,   85.00, 60, 'bottle', null,
   'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=800&auto=format&fit=crop&q=80',
   'Electrolyte replenishment — orange flavour.', 'Active'),
  ('Mixed Nuts Pack 200g', 'Food', 'Local',           380.00,  240.00, 30, 'packet', null,
   'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&auto=format&fit=crop&q=80',
   'Almonds, cashews, walnuts — healthy fats.', 'Active')
on conflict do nothing;

-- DONE. The Gym Shop page appears at /gym-shop after deploying this migration.
