-- Public catalogue access and customer order requests for the Gym Shop site.
-- Product costs and all other admin-only product data remain private.

revoke all on table public.shop_products from public, anon;
grant all on table public.shop_products to authenticated;
grant select (
  id, name, category, brand, price, stock, unit, size, image_url, description, status
) on public.shop_products to anon;

drop policy if exists "public read active shop products" on public.shop_products;
create policy "public read active shop products"
  on public.shop_products for select to anon
  using (status = 'Active');

create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  customer_name text not null check (char_length(trim(customer_name)) between 2 and 100),
  phone text not null check (char_length(trim(phone)) between 6 and 30),
  email text check (email is null or char_length(email) <= 254),
  delivery_address text not null check (char_length(trim(delivery_address)) between 4 and 500),
  customer_note text check (customer_note is null or char_length(customer_note) <= 1000),
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) between 1 and 20),
  total numeric(12, 2) not null check (total > 0),
  status text not null default 'New'
    check (status in ('New', 'Contacted', 'Completed', 'Cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists idx_shop_orders_created_at
  on public.shop_orders(created_at desc);

alter table public.shop_orders enable row level security;

drop policy if exists "authenticated read shop orders" on public.shop_orders;
create policy "authenticated read shop orders"
  on public.shop_orders for select to authenticated
  using (true);

drop policy if exists "authenticated update shop order status" on public.shop_orders;
create policy "authenticated update shop order status"
  on public.shop_orders for update to authenticated
  using (true)
  with check (status in ('New', 'Contacted', 'Completed', 'Cancelled'));

revoke all on table public.shop_orders from public, anon, authenticated;
grant select on public.shop_orders to authenticated;
grant update (status) on public.shop_orders to authenticated;
grant usage, select on sequence public.shop_orders_id_seq to authenticated;

create or replace function public.submit_shop_order(
  p_customer_name text,
  p_phone text,
  p_email text,
  p_delivery_address text,
  p_customer_note text,
  p_items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry jsonb;
  v_product record;
  v_product_id bigint;
  v_quantity int;
  v_seen_ids bigint[] := '{}';
  v_items jsonb := '[]'::jsonb;
  v_total numeric(12, 2) := 0;
  v_order_id bigint;
begin
  if char_length(trim(coalesce(p_customer_name, ''))) not between 2 and 100 then
    raise exception 'Please enter a name between 2 and 100 characters.';
  end if;
  if char_length(trim(coalesce(p_phone, ''))) not between 6 and 30 then
    raise exception 'Please enter a valid phone number.';
  end if;
  if p_email is not null and char_length(p_email) > 254 then
    raise exception 'Email address is too long.';
  end if;
  if char_length(trim(coalesce(p_delivery_address, ''))) not between 4 and 500 then
    raise exception 'Please enter a delivery address between 4 and 500 characters.';
  end if;
  if p_customer_note is not null and char_length(p_customer_note) > 1000 then
    raise exception 'Order note is too long.';
  end if;
  if jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) not between 1 and 20 then
    raise exception 'Your cart is empty or contains too many items.';
  end if;

  for v_entry in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := (v_entry->>'product_id')::bigint;
    v_quantity := (v_entry->>'quantity')::int;

    if v_product_id = any(v_seen_ids) then
      raise exception 'A product appears more than once in the cart.';
    end if;
    if v_quantity < 1 or v_quantity > 100 then
      raise exception 'Product quantities must be between 1 and 100.';
    end if;

    select id, name, category, brand, price, stock, unit, size, image_url
    into v_product
    from public.shop_products
    where id = v_product_id and status = 'Active';

    if not found then
      raise exception 'One of the products is no longer available.';
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Not enough stock for "%".', v_product.name;
    end if;

    v_seen_ids := array_append(v_seen_ids, v_product_id);
    v_total := v_total + v_product.price * v_quantity;
    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'productId', v_product.id,
      'name', v_product.name,
      'category', v_product.category,
      'brand', v_product.brand,
      'price', v_product.price,
      'quantity', v_quantity,
      'unit', v_product.unit,
      'size', v_product.size,
      'imageUrl', v_product.image_url
    ));
  end loop;

  insert into public.shop_orders (
    customer_name, phone, email, delivery_address, customer_note, items, total
  )
  values (
    trim(p_customer_name),
    trim(p_phone),
    nullif(trim(coalesce(p_email, '')), ''),
    trim(p_delivery_address),
    nullif(trim(coalesce(p_customer_note, '')), ''),
    v_items,
    v_total
  )
  returning id into v_order_id;

  return v_order_id;
end;
$$;

revoke all on function public.submit_shop_order(text, text, text, text, text, jsonb) from public;
grant execute on function public.submit_shop_order(text, text, text, text, text, jsonb) to anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'shop_products'
    ) then
    execute 'alter publication supabase_realtime add table public.shop_products';
  end if;
end;
$$;
